// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgqefqp8q9OMD12SdW29rBFZqEnVCa7Vs',
    appId: '1:982591339844:web:db0bf7bea38c820e806b11',
    messagingSenderId: '982591339844',
    projectId: 'finance-manager-fa074',
    authDomain: 'finance-manager-fa074.firebaseapp.com',
    storageBucket: 'finance-manager-fa074.firebasestorage.app',
    measurementId: 'G-FXRDEBX3J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo0KT9XSbY3cw9MSplH7RYbF92_bLskrs',
    appId: '1:982591339844:android:0e1d14127433513c806b11',
    messagingSenderId: '982591339844',
    projectId: 'finance-manager-fa074',
    storageBucket: 'finance-manager-fa074.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBomlTL2aiMik6_09KRbB8oEa3VvZoYRgo',
    appId: '1:982591339844:ios:e30059330b0dd974806b11',
    messagingSenderId: '982591339844',
    projectId: 'finance-manager-fa074',
    storageBucket: 'finance-manager-fa074.firebasestorage.app',
    iosBundleId: 'com.example.financeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaQ3uXhRhcooMw83oM1CfTn2wFbYuGekE',
    appId: '1:369783583830:ios:cf02ca9a23d7ba48cd77f7',
    messagingSenderId: '369783583830',
    projectId: 'finance-manager-56be4',
    storageBucket: 'finance-manager-56be4.firebasestorage.app',
    iosBundleId: 'com.example.financeManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmGmPovBbXATCpM5IsFP4MUtyjhUUSgHE',
    appId: '1:369783583830:web:8d51f35b332a6d93cd77f7',
    messagingSenderId: '369783583830',
    projectId: 'finance-manager-56be4',
    authDomain: 'finance-manager-56be4.firebaseapp.com',
    storageBucket: 'finance-manager-56be4.firebasestorage.app',
    measurementId: 'G-01SZS3WHH9',
  );
}